"""new fields in user model

Revision ID: 247d4b55662b
Revises: c8eeab24b960
Create Date: 2020-03-10 13:07:18.958580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '247d4b55662b'
down_revision = 'c8eeab24b960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
